from flask import Flask, request, redirect, render_template
from flask_sqlalchemy import SQLAlchemy


#connection string
#conect to mysql database by pymysql driver
#//username:password @ what server does it live on and port , name of database
#echo sql commands generated by sqlalchemy

app = Flask(__name__)
app.config['DEBUG'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://build-a-blog:launchcode@localhost:8889/build-a-blog'
app.config['SQLALCHEMY_ECHO'] = True
#calling SQLAchemy constructor and pass in the flask app
#create a database object to interface with database via python code
db = SQLAlchemy(app)

#set up data that can be stored inside a database by using a persistent class
#class reperesents data to store
#db is object that has a class model inside
#anytime a model class changed by adding/subtracting a column, you have to go in and db.drop/create_all() via python shell to reflect changes
class Blog(db.Model):

    #specify the data fields colums in this class
    #every class persistent/stored in a database will have a ID that functions as Primary key
    #id associated with the task class will go in to the designated column configured to a integer, and repersent the Primary key
    id = db.Column(db.Integer, primary_key=True)
     #name field column string data type with a max length of 120
    post_title = db.Column(db.String(245))
    #set completed database column
    #boolean to indicate if task has been completed
    post_body = db.Column(db.String(12000))

    #set constructor
    def __init__(self, title, body):
        self.post_title = title
        self.post_body = body
    #classes have to be caps

@app.route('/blog', methods = ['GET', 'POST'])
def index():

    posts = Blog.query.all()
    return render_template('blog.html', title="Build a Blog", posts=posts)

@app.route('/new-post', methods=['GET', 'POST'])
def new_post():

    post_body = ''
    post_title = ''
    error_title = ''
    error_blog = ''

    #obtain input data
    if request.method == 'POST':
        post_title = request.form['post_title']
        post_body = request.form['post_body']
        if post_title == '':
            error_title = 'You might need a Title!'
        elif post_body == '':
            error_blog = 'Your going to need to type some buttons!'
        else:
            #insert into database
            #commit database add
            new = Blog(post_title, post_body)
            db.session.add(new)
            db.session.commit()

            return redirect('/single-post?id={0}'.format(new.id))

    return render_template('new-post.html', title="New Post", error_title=error_title,
                error_blog=error_blog, post_title=post_title, post_body=post_body)

@app.route('/single-post', methods=['GET'])
def single_post():

    get_id = request.args.get('id')
    posts = db.session.query(Blog.post_title, Blog.post_body).filter_by(id=get_id)
    #redirect back to post page 
    return render_template('single-post.html', title="Single Post", posts=posts)

#allows importing objects,classes without running main.py
if __name__ == '__main__':
    app.run()